# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['MoralTopology']

# Cell
class MoralTopology:
    "MoralTopology class"
    def __init__(self, name, data):
        self.data = data
        self.name = name

    def username(self):
        return self.name